In [1]:
import torch


In [2]:
torch.version.__version__

'2.5.1'

In [3]:
a = torch.ones(3,3)

In [4]:
b = torch.ones(3,3)

In [5]:
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [6]:
if torch.cuda.is_available():
    print("CUDA is available!")
    a = a.to('cuda')
    b = b.to('cuda')
else:
    print("CUDA is not available.")
a + b

CUDA is not available.


tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [7]:
if torch.backends.mps.is_available():
    print("Apple Silicon (MPS backend) is available!")
    a = a.to('mps')
    b = b.to('mps')
else:
    print("Apple Silicon (MPS backend) is not available.")
a + b


Apple Silicon (MPS backend) is available!


tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='mps:0')